import os

lines = [
    "from http.server import BaseHTTPRequestHandler\n",
    "import json\n",
    "import urllib.request\n",
    "import urllib.error\n",
    "\n",
    "INVIDIOUS_INSTANCES = [\n",
    '    "https://yewtu.be",\n',
    '    "https://invidious.nerdvpn.de",\n',
    '    "https://inv.nadeko.net",\n',
    "]\n",
    "\n",
    "class handler(BaseHTTPRequestHandler):\n",
    "    def do_GET(self):\n",
    "        from urllib.parse import urlparse, parse_qs\n",
    "        parsed = urlparse(self.path)\n",
    "        params = parse_qs(parsed.query)\n",
    '        video_id = (params.get("videoId") or params.get("videoid") or [""])[0].strip()\n',
    '        title = (params.get("title") or ["lagu"])[0].strip()\n',
    "        if not video_id:\n",
    '            self._json(400, {"status": "error", "message": "videoId required"})\n',
    "            return\n",
    "        audio_info = self._get_audio_info(video_id)\n",
    "        if not audio_info:\n",
    '            self._json(502, {"status": "error", "message": "Tidak dapat mengambil audio"})\n',
    "            return\n",
    "        try:\n",
    "            req = urllib.request.Request(\n",
    '                audio_info["url"],\n',
    '                headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}\n',
    "            )\n",
    "            with urllib.request.urlopen(req, timeout=30) as audio_resp:\n",
    '                ct = audio_resp.headers.get("Content-Type", "audio/webm")\n',
    '                cl = audio_resp.headers.get("Content-Length", "")\n',
    '                ext = audio_info.get("ext", "webm")\n',
    '                safe = (audio_info.get("title") or title).replace(\'"\', "\'")[:80]\n',
    "                self.send_response(200)\n",
    '                self.send_header("Content-Type", ct)\n',
    '                self.send_header("Content-Disposition", \'attachment; filename="\' + safe + \'.\' + ext + \'"\')\n',
    "                if cl:\n",
    '                    self.send_header("Content-Length", cl)\n',
    "                self._cors()\n",
    "                self.end_headers()\n",
    "                while True:\n",
    "                    chunk = audio_resp.read(65536)\n",
    "                    if not chunk:\n",
    "                        break\n",
    "                    self.wfile.write(chunk)\n",
    "        except Exception as e:\n",
    '            self._json(502, {"status": "error", "message": str(e)[:200]})\n',
    "\n",
    "    def do_POST(self):\n",
    "        try:\n",
    "            length = int(self.headers.get('Content-Length', 0))\n",
    "            body = json.loads(self.rfile.read(length))\n",
    '            video_id = body.get("videoId", "").strip()\n',
    '            title = body.get("title", "lagu")\n',
    "            if not video_id:\n",
    '                self._json(400, {"status": "error", "message": "videoId required"})\n',
    "                return\n",
    "            audio_info = self._get_audio_info(video_id)\n",
    "            if audio_info:\n",
    "                self._json(200, {\n",
    '                    "status": "success",\n',
    '                    "url": audio_info["url"],\n',
    '                    "title": audio_info.get("title") or title,\n',
    '                    "ext": audio_info.get("ext", "webm"),\n',
    "                })\n",
    "            else:\n",
    '                self._json(502, {"status": "error", "message": "Tidak dapat mengambil audio"})\n',
    "        except Exception as e:\n",
    '            self._json(500, {"status": "error", "message": str(e)[:200]})\n',
    "\n",
    "    def _get_audio_info(self, video_id):\n",
    "        for instance in INVIDIOUS_INSTANCES:\n",
    "            try:\n",
    '                url = instance + "/api/v1/videos/" + video_id + "?fields=title,adaptiveFormats"\n',
    "                req = urllib.request.Request(\n",
    "                    url,\n",
    '                    headers={"User-Agent": "Mozilla/5.0 (compatible; Auspoty/1.0)", "Accept": "application/json"}\n',
    "                )\n",
    "                with urllib.request.urlopen(req, timeout=12) as resp:\n",
    "                    data = json.loads(resp.read().decode())\n",
    '                formats = data.get("adaptiveFormats", [])\n',
    "                audio_formats = [\n",
    "                    f for f in formats\n",
    '                    if f.get("type", "").startswith("audio/") and f.get("url")\n',
    "                ]\n",
    "                if not audio_formats:\n",
    "                    continue\n",
    "                def get_bitrate(f):\n",
    "                    try:\n",
    '                        return int(f.get("bitrate", "0"))\n',
    "                    except Exception:\n",
    "                        return 0\n",
    "                audio_formats.sort(key=get_bitrate, reverse=True)\n",
    "                best = audio_formats[0]\n",
    '                mime = best.get("type", "audio/webm")\n',
    '                ext = "webm"\n',
    '                if "mp4" in mime or "m4a" in mime:\n',
    '                    ext = "m4a"\n',
    '                elif "opus" in mime:\n',
    '                    ext = "opus"\n',
    '                return {"url": best["url"], "title": data.get("title", ""), "ext": ext}\n',
    "            except Exception:\n",
    "                continue\n",
    "        return None\n",
    "\n",
    "    def do_OPTIONS(self):\n",
    "        self.send_response(200)\n",
    "        self._cors()\n",
    "        self.end_headers()\n",
    "\n",
    "    def _cors(self):\n",
    '        self.send_header("Access-Control-Allow-Origin", "*")\n',
    '        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")\n',
    '        self.send_header("Access-Control-Allow-Headers", "Content-Type")\n',
    "\n",
    "    def _json(self, code, data):\n",
    "        body = json.dumps(data).encode()\n",
    "        self.send_response(code)\n",
    "        self._cors()\n",
    '        self.send_header("Content-Type", "application/json")\n',
    '        self.send_header("Content-Length", str(len(body)))\n',
    "        self.end_headers()\n",
    "        self.wfile.write(body)\n",
]

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "api", "download.py")
with open(out, "w", encoding="utf-8") as f:
    f.writelines(lines)
print("Written:", out)
print("Lines:", len(lines))
