import os

lines = [
    "from http.server import BaseHTTPRequestHandler\n",
    "import json, urllib.request, urllib.error, time, random\n",
    "\n",
    "HEADERS = {\n",
    "    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120',\n",
    "    'Referer': 'https://id.ytmp3.mobi/v1/',\n",
    "    'Origin': 'https://id.ytmp3.mobi',\n",
    "}\n",
    "\n",
    "def ymcdn_get(url):\n",
    "    req = urllib.request.Request(url, headers=HEADERS)\n",
    "    r = urllib.request.urlopen(req, timeout=15)\n",
    "    return json.loads(r.read().decode())\n",
    "\n",
    "def get_mp3_url(video_id):\n",
    "    rnd = random.random()\n",
    "    init = ymcdn_get('https://a.ymcdn.org/api/v1/init?p=y&23=1llum1n471&_=' + str(rnd))\n",
    "    if init.get('error', 0) > 0:\n",
    "        raise Exception('init error: ' + str(init.get('error')))\n",
    "    convert_url = init['convertURL']\n",
    "    rnd2 = random.random()\n",
    "    conv = ymcdn_get(convert_url + '&v=' + video_id + '&f=mp3&_=' + str(rnd2))\n",
    "    if conv.get('error', 0) > 0:\n",
    "        raise Exception('convert error: ' + str(conv.get('error')))\n",
    "    title = conv.get('title', video_id)\n",
    "    progress_url = conv['progressURL']\n",
    "    download_url = conv['downloadURL']\n",
    "    for _ in range(30):\n",
    "        time.sleep(1)\n",
    "        prog = ymcdn_get(progress_url + '&_=' + str(random.random()))\n",
    "        if prog.get('error', 0) > 0:\n",
    "            raise Exception('progress error: ' + str(prog.get('error')))\n",
    "        if prog.get('progress', 0) >= 3:\n",
    "            return prog.get('downloadURL') or download_url, title\n",
    "    raise Exception('timeout waiting for conversion')\n",
    "\n",
    "class handler(BaseHTTPRequestHandler):\n",
    "    def do_POST(self):\n",
    "        try:\n",
    "            length = int(self.headers.get('Content-Length', 0))\n",
    "            body = json.loads(self.rfile.read(length))\n",
    "            video_id = body.get('videoId', '').strip()\n",
    "            if not video_id:\n",
    "                self._json(400, {'status': 'error', 'message': 'videoId required'})\n",
    "                return\n",
    "            dl_url, title = get_mp3_url(video_id)\n",
    "            self._json(200, {'status': 'success', 'url': dl_url, 'title': title, 'ext': 'mp3'})\n",
    "        except Exception as e:\n",
    "            self._json(500, {'status': 'error', 'message': str(e)[:200]})\n",
    "\n",
    "    def do_OPTIONS(self):\n",
    "        self.send_response(200)\n",
    "        self._cors()\n",
    "        self.end_headers()\n",
    "\n",
    "    def _cors(self):\n",
    "        self.send_header('Access-Control-Allow-Origin', '*')\n",
    "        self.send_header('Access-Control-Allow-Methods', 'POST, OPTIONS')\n",
    "        self.send_header('Access-Control-Allow-Headers', 'Content-Type')\n",
    "\n",
    "    def _json(self, code, data):\n",
    "        body = json.dumps(data).encode()\n",
    "        self.send_response(code)\n",
    "        self._cors()\n",
    "        self.send_header('Content-Type', 'application/json')\n",
    "        self.send_header('Content-Length', str(len(body)))\n",
    "        self.end_headers()\n",
    "        self.wfile.write(body)\n",
]

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "api", "download.py")
with open(out, "w", encoding="utf-8") as f:
    f.writelines(lines)
print("Written:", out)
